### ISSUE TITLE
Wong service reference on documentation

### ISSUE THREAD

**Issue by FlavioCFOliveira** [bhamail/pinexus#6]
Hi,

I'm installing the PiNexus on my new rpi4 4Gb with Raspbian Buster Lite (Version: February 2020) and i found after analizing the instalation log that on documentation (http://bhamail.github.io/pinexus/nexussetup.html) is mentioned: 

`sudo service nexus3 stop`

but the service created has a different name as follows in the example:

`
Setting up nexus-repository-manager (3.22.002-2) ...
post configure
Created symlink /etc/systemd/system/multi-user.target.wants/nexus-repository-manager.service → /opt/sonatype/nexus3/e                                                                                                                        xtra/daemon/nexus-repository-manager.service.
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for systemd (241-7~deb10u3+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for ca-certificates (20190110) ...
Updating certificates in /etc/ssl/certs...
`

Can you please fix or the service name on the package post install or the documentation?

**Comment by bhamail** [comment]
Aha! Nice catch. Thanks for reporting this. When I recently switched to using the native installer, I totally missed this. The service name in the documentation should be: `nexus-repository-manager`

For example:
```
$ sudo service nexus-repository-manager status
● nexus-repository-manager.service - Nexus Repository Manager 3 Service
   Loaded: loaded (/opt/sonatype/nexus3/extra/daemon/nexus-repository-manager.se
   Active: active (running) since Sat 2020-03-28 22:22:17 EDT; 5 days ago
 Main PID: 23184 (java)
    Tasks: 108 (limit: 2200)
   Memory: 587.9M
   CGroup: /system.slice/nexus-repository-manager.service
           └─23184 /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java -server -Dinst

Mar 28 22:22:17 raspberrypi-nexus3 systemd[1]: Starting Nexus Repository Manager
Mar 28 22:22:17 raspberrypi-nexus3 nexus[22996]: Starting nexus
Mar 28 22:22:17 raspberrypi-nexus3 systemd[1]: Started Nexus Repository Manager
```

I'm running around a little crazier that usual right now. If you'd like to take a shot at creating a Pull Request to fix this, I'd be happy to help with a review, etc.

**Comment by bhamail** [comment]
@FlavioCFOliveira While I was looking into this, I discovered some other problems regarding memory settings. Yikes! I'd have never found any of this if not for this issue you filed. Thank You! I hop you don't mind, I went ahead and updated the service name bug while I was in there.
