### ISSUE TITLE
Add Apt repository configuration on step 2

### ISSUE THREAD

**Issue by FlavioCFOliveira** [bhamail/pinexus#8]
As a suggestion to help during the installation, on the nexus setup page, before the apt install add the instructions to:

- Add how users should download and install the asc key;
- Add sonatype-community.list to the /etc/apt/sources.list.d/ directory - call apt update before apt install

**Comment by bhamail** [comment]
I see your point. There are instructions at the installer project here:
https://github.com/sonatype-nexus-community/nexus-repository-installer#apt-setup
, which I recently updated with the `update` command thanks to your reports.

I want to balance providing the information needed with avoiding duplication. Perhaps a link out to those instructions would be the best of both worlds? (I would welcome a PR if you can).

**Comment by FlavioCFOliveira** [comment]
ok, i understand, i will send a PR, just for your consideration

**Comment by bhamail** [comment]
Fixed in 0cb0cac2cb1628a9144e880ce66abfb8828417ee
